run:
  deadline: 2m
  tests: false
  skip-dirs:
    - assets
    - dev
    - proto
    - mocks

issues:
  exclude-use-default: false
  exclude:
    - G104
    - should have a package comment
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - lll
    - maligned
    - prealloc
    - gochecknoglobals
    - gochecknoinits
    - godox
    - whitespace
    - wsl
    - funlen
    - gocognit
