version: '3'

services:
  server:
    command: go run main.go --debug server
    build: .
    image: orion_app
    volumes:
      - .:/opt/build
    environment:
      SERVICE_NAME: orion-server
      DEV_STORAGE: s3

  postgresql:
    image: mdillon/postgis:11-alpine
    environment:
      - POSTGRES_USER=syncano
      - POSTGRES_PASSWORD=syncano
      - POSTGRES_DB=syncano
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432"

  redis:
    image: redis:5-alpine
    volumes:
      - data-redis:/data
    ports:
      - "6379"

  rabbitmq:
    image: rabbitmq:3.8-alpine
    volumes:
      - data-rabbitmq:/data
    ports:
      - "5672"
      - "15672"

  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "16686:16686"
      - "14268:14268"
      - "14250"
      - "9411:9411"

volumes:
  data-rabbitmq:
  data-redis:
