version: 2.1
jobs:
  test:
    machine: true
    steps:
      - checkout

      - run:
          name: Build application Docker image
          command: docker-compose build

      - run:
          name: Lint
          command: |
            make lint-in-docker

      - run:
          name: Test
          command: |
            make test-in-docker

  deploy:
    machine: true
    steps:
      - checkout

      - run:
          name: Setup system
          command: |
              docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASS" $DOCKER_SERVER
      - run:
          name: Build application Docker image
          command: |
            docker-compose build
      - run:
          name: Build static version and create target image
          command: |
            make build-in-docker docker

      - run:
          name: Install jinja2-cli
          command: |
            pip install jinja2-cli[yaml]
      - run:
          name: Install gcloud and kubectl
          command: |
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
            sudo /opt/google-cloud-sdk/bin/gcloud --quiet components install kubectl
            sudo chown circleci:circleci ~/.config/gcloud/ -R

      - run:
          name: Build and deploy
          command: |
            make decrypt

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              echo $GCLOUD_STG_SERVICE_KEY > gcloud-service-key.json
              gcloud auth activate-service-account --key-file=gcloud-service-key.json
              gcloud container clusters get-credentials syncano-stg --zone europe-west1 --project syncano-staging

              make deploy-staging

            elif [ "$CIRCLE_BRANCH" == "stable" ]; then
              echo $GCLOUD_EU1_SERVICE_KEY > gcloud-service-key.json
              gcloud auth activate-service-account --key-file=gcloud-service-key.json
              gcloud container clusters get-credentials syncano-eu1 --zone europe-west1 --project pioner-syncano-prod-9cfb

              make deploy-production
            fi

            make clean

workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
                - stable

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - stable
