// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/proto/codebox/lb/runner.proto

package lb

import (
	context "context"
	fmt "fmt"
	script "github.com/Syncano/orion/app/proto/codebox/script"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RunRequest represents either a Meta message or a Chunk message.
// It should always consist of exactly 1 Meta and optionally repeated Chunk messages.
type RunRequest struct {
	// Types that are valid to be assigned to Value:
	//	*RunRequest_Meta
	//	*RunRequest_Request
	Value                isRunRequest_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6192596860f0a49, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

type isRunRequest_Value interface {
	isRunRequest_Value()
}

type RunRequest_Meta struct {
	Meta *RunRequest_MetaMessage `protobuf:"bytes,1,opt,name=meta,proto3,oneof"`
}

type RunRequest_Request struct {
	Request *script.RunRequest `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

func (*RunRequest_Meta) isRunRequest_Value() {}

func (*RunRequest_Request) isRunRequest_Value() {}

func (m *RunRequest) GetValue() isRunRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RunRequest) GetMeta() *RunRequest_MetaMessage {
	if x, ok := m.GetValue().(*RunRequest_Meta); ok {
		return x.Meta
	}
	return nil
}

func (m *RunRequest) GetRequest() *script.RunRequest {
	if x, ok := m.GetValue().(*RunRequest_Request); ok {
		return x.Request
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RunRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RunRequest_Meta)(nil),
		(*RunRequest_Request)(nil),
	}
}

// Meta message specifies fields to describe what is being run.
type RunRequest_MetaMessage struct {
	ConcurrencyKey       string   `protobuf:"bytes,1,opt,name=concurrencyKey,proto3" json:"concurrencyKey,omitempty"`
	ConcurrencyLimit     int32    `protobuf:"varint,2,opt,name=concurrencyLimit,proto3" json:"concurrencyLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest_MetaMessage) Reset()         { *m = RunRequest_MetaMessage{} }
func (m *RunRequest_MetaMessage) String() string { return proto.CompactTextString(m) }
func (*RunRequest_MetaMessage) ProtoMessage()    {}
func (*RunRequest_MetaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6192596860f0a49, []int{0, 0}
}

func (m *RunRequest_MetaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest_MetaMessage.Unmarshal(m, b)
}
func (m *RunRequest_MetaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest_MetaMessage.Marshal(b, m, deterministic)
}
func (m *RunRequest_MetaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest_MetaMessage.Merge(m, src)
}
func (m *RunRequest_MetaMessage) XXX_Size() int {
	return xxx_messageInfo_RunRequest_MetaMessage.Size(m)
}
func (m *RunRequest_MetaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest_MetaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest_MetaMessage proto.InternalMessageInfo

func (m *RunRequest_MetaMessage) GetConcurrencyKey() string {
	if m != nil {
		return m.ConcurrencyKey
	}
	return ""
}

func (m *RunRequest_MetaMessage) GetConcurrencyLimit() int32 {
	if m != nil {
		return m.ConcurrencyLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "lb.RunRequest")
	proto.RegisterType((*RunRequest_MetaMessage)(nil), "lb.RunRequest.MetaMessage")
}

func init() { proto.RegisterFile("app/proto/codebox/lb/runner.proto", fileDescriptor_f6192596860f0a49) }

var fileDescriptor_f6192596860f0a49 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0x33, 0x31,
	0x10, 0x87, 0xbb, 0x7d, 0xdf, 0x5a, 0x9c, 0x4a, 0x91, 0x78, 0x29, 0x7b, 0x52, 0x41, 0x29, 0x82,
	0x49, 0xa9, 0x77, 0x0f, 0x3d, 0x15, 0xb4, 0x97, 0xf4, 0xe6, 0x2d, 0x89, 0x43, 0x5d, 0xd8, 0xcd,
	0xc4, 0xfc, 0x11, 0xf7, 0xab, 0xfa, 0x69, 0x84, 0x6c, 0xa5, 0xad, 0xf5, 0x14, 0x78, 0xe6, 0x99,
	0xfc, 0x26, 0x19, 0xb8, 0x52, 0xce, 0x09, 0xe7, 0x29, 0x92, 0x30, 0xf4, 0x8a, 0x9a, 0x3e, 0x45,
	0xad, 0x85, 0x4f, 0xd6, 0xa2, 0xe7, 0x99, 0xb3, 0x7e, 0xad, 0xcb, 0x9b, 0x63, 0x2d, 0x18, 0x5f,
	0xb9, 0xb8, 0x3d, 0x3a, 0xf5, 0xfa, 0xab, 0x00, 0x90, 0xc9, 0x4a, 0x7c, 0x4f, 0x18, 0x22, 0x9b,
	0xc1, 0xff, 0x06, 0xa3, 0x9a, 0x14, 0x97, 0xc5, 0x74, 0x34, 0x2f, 0x79, 0xad, 0xf9, 0xae, 0xca,
	0x57, 0x18, 0xd5, 0x0a, 0x43, 0x50, 0x1b, 0x5c, 0xf6, 0x64, 0x36, 0x19, 0x87, 0xa1, 0xef, 0xca,
	0x93, 0x7e, 0x6e, 0x62, 0x7c, 0x1b, 0xb0, 0x6b, 0x5c, 0xf6, 0xe4, 0x8f, 0x54, 0x2a, 0x18, 0xed,
	0x5d, 0xc3, 0x6e, 0x61, 0x6c, 0xc8, 0x9a, 0xe4, 0x3d, 0x5a, 0xd3, 0x3e, 0x61, 0x9b, 0xa3, 0x4f,
	0xe5, 0x2f, 0xca, 0xee, 0xe0, 0x7c, 0x8f, 0x3c, 0x57, 0x4d, 0xd5, 0xe5, 0x0d, 0xe4, 0x11, 0x5f,
	0x0c, 0x61, 0xf0, 0xa1, 0xea, 0x84, 0xf3, 0x47, 0x38, 0x5b, 0xe7, 0x59, 0x64, 0xfe, 0x1d, 0xc6,
	0xe1, 0x9f, 0x4c, 0x96, 0x8d, 0x0f, 0x9f, 0x55, 0x5e, 0x1c, 0x4c, 0x1c, 0x1c, 0xd9, 0x80, 0xd3,
	0x62, 0x56, 0x2c, 0xc4, 0xcb, 0xfd, 0xa6, 0x8a, 0x6f, 0x49, 0x73, 0x43, 0x8d, 0x58, 0xb7, 0xd6,
	0x28, 0x4b, 0x82, 0x7c, 0x45, 0x56, 0xfc, 0xb5, 0x05, 0x7d, 0x92, 0xc9, 0xc3, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x36, 0x51, 0xe3, 0x59, 0xa4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScriptRunnerClient is the client API for ScriptRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScriptRunnerClient interface {
	// Run runs script in secure environment of worker.
	Run(ctx context.Context, opts ...grpc.CallOption) (ScriptRunner_RunClient, error)
}

type scriptRunnerClient struct {
	cc *grpc.ClientConn
}

func NewScriptRunnerClient(cc *grpc.ClientConn) ScriptRunnerClient {
	return &scriptRunnerClient{cc}
}

func (c *scriptRunnerClient) Run(ctx context.Context, opts ...grpc.CallOption) (ScriptRunner_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ScriptRunner_serviceDesc.Streams[0], "/lb.ScriptRunner/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &scriptRunnerRunClient{stream}
	return x, nil
}

type ScriptRunner_RunClient interface {
	Send(*RunRequest) error
	Recv() (*script.RunResponse, error)
	grpc.ClientStream
}

type scriptRunnerRunClient struct {
	grpc.ClientStream
}

func (x *scriptRunnerRunClient) Send(m *RunRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *scriptRunnerRunClient) Recv() (*script.RunResponse, error) {
	m := new(script.RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ScriptRunnerServer is the server API for ScriptRunner service.
type ScriptRunnerServer interface {
	// Run runs script in secure environment of worker.
	Run(ScriptRunner_RunServer) error
}

func RegisterScriptRunnerServer(s *grpc.Server, srv ScriptRunnerServer) {
	s.RegisterService(&_ScriptRunner_serviceDesc, srv)
}

func _ScriptRunner_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ScriptRunnerServer).Run(&scriptRunnerRunServer{stream})
}

type ScriptRunner_RunServer interface {
	Send(*script.RunResponse) error
	Recv() (*RunRequest, error)
	grpc.ServerStream
}

type scriptRunnerRunServer struct {
	grpc.ServerStream
}

func (x *scriptRunnerRunServer) Send(m *script.RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *scriptRunnerRunServer) Recv() (*RunRequest, error) {
	m := new(RunRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ScriptRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lb.ScriptRunner",
	HandlerType: (*ScriptRunnerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _ScriptRunner_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "app/proto/codebox/lb/runner.proto",
}
