// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app/proto/codebox/broker/broker.proto

package broker

import (
	context "context"
	fmt "fmt"
	lb "github.com/Syncano/orion/app/proto/codebox/lb"
	script "github.com/Syncano/orion/app/proto/codebox/script"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RunRequest represents either a Meta message or a Chunk message.
// It should always consist of exactly 1 Meta and optionally repeated Chunk messages.
type RunRequest struct {
	Meta                 *RunRequest_MetaMessage    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	LbMeta               *lb.RunRequest_MetaMessage `protobuf:"bytes,2,opt,name=lbMeta,proto3" json:"lbMeta,omitempty"`
	Request              []*script.RunRequest       `protobuf:"bytes,3,rep,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8362f49ed7d1d7a, []int{0}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetMeta() *RunRequest_MetaMessage {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *RunRequest) GetLbMeta() *lb.RunRequest_MetaMessage {
	if m != nil {
		return m.LbMeta
	}
	return nil
}

func (m *RunRequest) GetRequest() []*script.RunRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

// Meta message specifies fields to describe what is being run.
type RunRequest_MetaMessage struct {
	Files                map[string]string `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	EnvironmentURL       string            `protobuf:"bytes,2,opt,name=environmentURL,proto3" json:"environmentURL,omitempty"`
	Trace                []byte            `protobuf:"bytes,3,opt,name=trace,proto3" json:"trace,omitempty"`
	TraceID              uint64            `protobuf:"varint,4,opt,name=traceID,proto3" json:"traceID,omitempty"`
	Sync                 bool              `protobuf:"varint,5,opt,name=sync,proto3" json:"sync,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RunRequest_MetaMessage) Reset()         { *m = RunRequest_MetaMessage{} }
func (m *RunRequest_MetaMessage) String() string { return proto.CompactTextString(m) }
func (*RunRequest_MetaMessage) ProtoMessage()    {}
func (*RunRequest_MetaMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8362f49ed7d1d7a, []int{0, 0}
}

func (m *RunRequest_MetaMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest_MetaMessage.Unmarshal(m, b)
}
func (m *RunRequest_MetaMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest_MetaMessage.Marshal(b, m, deterministic)
}
func (m *RunRequest_MetaMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest_MetaMessage.Merge(m, src)
}
func (m *RunRequest_MetaMessage) XXX_Size() int {
	return xxx_messageInfo_RunRequest_MetaMessage.Size(m)
}
func (m *RunRequest_MetaMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest_MetaMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest_MetaMessage proto.InternalMessageInfo

func (m *RunRequest_MetaMessage) GetFiles() map[string]string {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *RunRequest_MetaMessage) GetEnvironmentURL() string {
	if m != nil {
		return m.EnvironmentURL
	}
	return ""
}

func (m *RunRequest_MetaMessage) GetTrace() []byte {
	if m != nil {
		return m.Trace
	}
	return nil
}

func (m *RunRequest_MetaMessage) GetTraceID() uint64 {
	if m != nil {
		return m.TraceID
	}
	return 0
}

func (m *RunRequest_MetaMessage) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func init() {
	proto.RegisterType((*RunRequest)(nil), "broker.RunRequest")
	proto.RegisterType((*RunRequest_MetaMessage)(nil), "broker.RunRequest.MetaMessage")
	proto.RegisterMapType((map[string]string)(nil), "broker.RunRequest.MetaMessage.FilesEntry")
}

func init() {
	proto.RegisterFile("app/proto/codebox/broker/broker.proto", fileDescriptor_f8362f49ed7d1d7a)
}

var fileDescriptor_f8362f49ed7d1d7a = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xfb, 0x30,
	0x18, 0xc6, 0xc9, 0xda, 0x6d, 0xff, 0xbd, 0x1b, 0x7f, 0x24, 0x7a, 0x08, 0x3d, 0x48, 0x15, 0x94,
	0x0a, 0xd2, 0xce, 0xee, 0x32, 0xbc, 0x28, 0xa2, 0x82, 0xe0, 0x2e, 0x19, 0x5e, 0xbc, 0xb5, 0x35,
	0xce, 0xb2, 0x2e, 0xa9, 0x49, 0x3a, 0xec, 0x47, 0xf1, 0x7b, 0xfa, 0x01, 0xa4, 0x69, 0xc7, 0xd4,
	0x39, 0x4f, 0x79, 0x9f, 0x37, 0xbf, 0x27, 0x79, 0xfa, 0x36, 0x70, 0x14, 0xe5, 0x79, 0x90, 0x4b,
	0xa1, 0x45, 0x90, 0x88, 0x27, 0x16, 0x8b, 0xb7, 0x20, 0x96, 0x62, 0xce, 0x64, 0xb3, 0xf8, 0x66,
	0x0f, 0x77, 0x6a, 0xe5, 0x1c, 0x6c, 0xe2, 0x59, 0x1c, 0xc8, 0x82, 0xf3, 0x15, 0xea, 0xfc, 0x72,
	0xa2, 0x4a, 0x64, 0x9a, 0xeb, 0x66, 0xa9, 0xb1, 0xc3, 0x77, 0x0b, 0x80, 0x16, 0x9c, 0xb2, 0xd7,
	0x82, 0x29, 0x8d, 0x43, 0xb0, 0x17, 0x4c, 0x47, 0x04, 0xb9, 0xc8, 0xeb, 0x87, 0xfb, 0x7e, 0x73,
	0xfb, 0x9a, 0xf0, 0x27, 0x4c, 0x47, 0x13, 0xa6, 0x54, 0x34, 0x63, 0xd4, 0xb0, 0x38, 0x84, 0x4e,
	0x16, 0x57, 0x6d, 0xd2, 0x32, 0x2e, 0xc7, 0xcf, 0xe2, 0x6d, 0x8e, 0x86, 0xc4, 0xa7, 0xd0, 0x95,
	0xf5, 0x36, 0xb1, 0x5c, 0xcb, 0xeb, 0x87, 0xd8, 0x6f, 0x62, 0xad, 0x8d, 0x74, 0x85, 0x38, 0x1f,
	0x08, 0xfa, 0x5f, 0x4e, 0xc1, 0x17, 0xd0, 0x7e, 0x4e, 0x33, 0xa6, 0x08, 0x32, 0xde, 0x93, 0xbf,
	0x63, 0xfa, 0xb7, 0x15, 0x7b, 0xc3, 0xb5, 0x2c, 0x69, 0xed, 0xc3, 0xc7, 0xf0, 0x9f, 0xf1, 0x65,
	0x2a, 0x05, 0x5f, 0x30, 0xae, 0x1f, 0xe8, 0xbd, 0x89, 0xde, 0xa3, 0x3f, 0xba, 0x78, 0x0f, 0xda,
	0x5a, 0x46, 0x09, 0x23, 0x96, 0x8b, 0xbc, 0x01, 0xad, 0x05, 0x26, 0xd0, 0x35, 0xc5, 0xdd, 0x35,
	0xb1, 0x5d, 0xe4, 0xd9, 0x74, 0x25, 0x31, 0x06, 0x5b, 0x95, 0x3c, 0x21, 0x6d, 0x17, 0x79, 0xff,
	0xa8, 0xa9, 0x9d, 0x31, 0xc0, 0x3a, 0x00, 0xde, 0x01, 0x6b, 0xce, 0x4a, 0x33, 0xdf, 0x1e, 0xad,
	0xca, 0xea, 0x8e, 0x65, 0x94, 0x15, 0xac, 0x89, 0x50, 0x8b, 0xf3, 0xd6, 0x18, 0x85, 0x97, 0x30,
	0x98, 0x9a, 0xa1, 0x50, 0xf3, 0x63, 0xf1, 0x10, 0x2c, 0x5a, 0x70, 0x8c, 0x37, 0x3f, 0xd7, 0xd9,
	0xfd, 0x36, 0x3e, 0x95, 0x0b, 0xae, 0xd8, 0x10, 0x5d, 0x8d, 0x1e, 0xcf, 0x66, 0xa9, 0x7e, 0x29,
	0x62, 0x3f, 0x11, 0x8b, 0x60, 0x5a, 0xf2, 0x24, 0xe2, 0x22, 0x10, 0x32, 0x15, 0x3c, 0xd8, 0xf6,
	0xe2, 0xe2, 0x8e, 0xe9, 0x8e, 0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xfa, 0xe1, 0x1d, 0x94,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScriptRunnerClient is the client API for ScriptRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScriptRunnerClient interface {
	// Run runs script in secure environment.
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (ScriptRunner_RunClient, error)
}

type scriptRunnerClient struct {
	cc *grpc.ClientConn
}

func NewScriptRunnerClient(cc *grpc.ClientConn) ScriptRunnerClient {
	return &scriptRunnerClient{cc}
}

func (c *scriptRunnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (ScriptRunner_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ScriptRunner_serviceDesc.Streams[0], "/broker.ScriptRunner/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &scriptRunnerRunClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ScriptRunner_RunClient interface {
	Recv() (*script.RunResponse, error)
	grpc.ClientStream
}

type scriptRunnerRunClient struct {
	grpc.ClientStream
}

func (x *scriptRunnerRunClient) Recv() (*script.RunResponse, error) {
	m := new(script.RunResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ScriptRunnerServer is the server API for ScriptRunner service.
type ScriptRunnerServer interface {
	// Run runs script in secure environment.
	Run(*RunRequest, ScriptRunner_RunServer) error
}

func RegisterScriptRunnerServer(s *grpc.Server, srv ScriptRunnerServer) {
	s.RegisterService(&_ScriptRunner_serviceDesc, srv)
}

func _ScriptRunner_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScriptRunnerServer).Run(m, &scriptRunnerRunServer{stream})
}

type ScriptRunner_RunServer interface {
	Send(*script.RunResponse) error
	grpc.ServerStream
}

type scriptRunnerRunServer struct {
	grpc.ServerStream
}

func (x *scriptRunnerRunServer) Send(m *script.RunResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ScriptRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "broker.ScriptRunner",
	HandlerType: (*ScriptRunnerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _ScriptRunner_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app/proto/codebox/broker/broker.proto",
}
