// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import (
	amqp "github.com/streadway/amqp"

	mock "github.com/stretchr/testify/mock"
)

// AMQPChannel is an autogenerated mock type for the AMQPChannel type
type AMQPChannel struct {
	mock.Mock
}

// Publish provides a mock function with given fields: exchange, key, mandatory, immediate, msg
func (_m *AMQPChannel) Publish(exchange string, key string, mandatory bool, immediate bool, msg amqp.Publishing) error {
	ret := _m.Called(exchange, key, mandatory, immediate, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, bool, bool, amqp.Publishing) error); ok {
		r0 = rf(exchange, key, mandatory, immediate, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
